# These are supported funding model platforms

github: [daniel-griffiths] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: danielgriffiths # Replace with a single Ko-fi username
custom: ['https://www.paypal.me/danielgriffithsdev'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
